// Vue/src/components/LabReportModal.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { BenchmarkResult } from '../types';
import { X, FileText, Download, Copy, Check, User, GraduationCap, Calendar } from 'lucide-vue-next';

const props = defineProps<{
  isOpen: boolean;
  benchmarkResults: BenchmarkResult[];
}>();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const studentName = ref('Alex Morgan');
const studentId = ref('CS-2026-8942');
const courseName = ref('CS480: Advanced Front-End Web Architecture');
const copied = ref(false);

const markdownReport = computed(() => {
  const now = new Date().toLocaleDateString();
  let text = `# DOM Benchmark & Performance Analysis Lab Report
**Student Name:** ${studentName.value || 'N/A'}
**Student ID:** ${studentId.value || 'N/A'}
**Course:** ${courseName.value || 'N/A'}
**Date Generated:** ${now}

---

## 1. Executive Summary
This lab evaluates DOM manipulation efficiency across React, Angular, Vue 3, and Svelte under heavy structural mutations.

## 2. Benchmark Measurement Matrix
| Framework | Operation | Task Count | Execution Time (ms) | DOM Mutations | Memory Est (KB) |
| :--- | :--- | :--- | :--- | :--- | :--- |
`;

  if (props.benchmarkResults.length === 0) {
    text += `| No benchmark data available. Execute the test suite to populate measurements. |\n`;
  } else {
    props.benchmarkResults.forEach((res) => {
      text += `| **${res.framework.toUpperCase()}** | ${res.op} | ${res.itemCount} | ${res.durationMs} ms | ${res.domMutations} ops | ${res.memoryEstKb} KB |\n`;
    });
  }

  text += `
---

## 3. Framework Architectural Findings

### React (Fiber & Virtual DOM Reconciliation)
- Uses Virtual DOM diffing algorithm to calculate minimal patches.
- Incurred higher garbage collection pressure during large initial batch allocations.

### Angular (Ivy Engine & Signals)
- Uses compiled incremental DOM instructions with tracking keys.
- Shows predictable rendering times, but has higher initial memory overhead due to LView tree metadata.

### Vue 3 (Reactive Proxies & Compiler Block Tree)
- Leverages dynamic slot flags in its Block Tree to skip static elements.
- Demonstrates fast patching performance for granular mutations.

### Svelte (Compiled Imperative DOM)
- Compiles components into direct imperative DOM manipulation code without a Virtual DOM layer.
- Achieved the lowest execution latency and smallest memory footprint across initial mounts and updates.

---

## 4. Student Reflection & Conclusion
Based on empirical DOM mutation tracking and browser paint cycle profiling, Svelte and Vue 3 demonstrate optimal performance for high-frequency DOM list re-renderings due to direct reactive bindings and compiler optimization.
`;

  return text;
});

function handleCopyMarkdown() {
  navigator.clipboard.writeText(markdownReport.value);
  copied.value = true;
  setTimeout(() => {
    copied.value = false;
  }, 2000);
}

function handleDownloadJson() {
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(props.benchmarkResults, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `dom_benchmark_report_${Date.now()}.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}
</script>

<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
    <div class="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
      <!-- Modal Header -->
      <div class="p-5 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-lg bg-amber-100 text-amber-800 flex items-center justify-center border border-amber-200 shadow-xs">
            <FileText class="w-5 h-5" />
          </div>
          <div>
            <h2 class="text-base font-bold text-slate-900">Student Lab Report & Export</h2>
            <p class="text-xs text-slate-500">Generate formatted coursework report & export benchmark logs</p>
          </div>
        </div>
        <button
          @click="emit('close')"
          class="p-2 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-200/60 transition-all"
        >
          <X class="w-5 h-5" />
        </button>
      </div>

      <div class="p-6 overflow-y-auto space-y-6 flex-1">
        <!-- Student Information Input Card -->
        <div class="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-3">
          <div class="text-xs font-semibold text-slate-700 uppercase tracking-wider font-mono">
            Student & Coursework Identifiers
          </div>
          <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label class="block text-[11px] font-semibold text-slate-600 mb-1 flex items-center gap-1">
                <User class="w-3 h-3 text-slate-400" />
                Student Name
              </label>
              <input
                v-model="studentName"
                type="text"
                class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-lg text-xs font-medium text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                placeholder="Enter your name"
              />
            </div>

            <div>
              <label class="block text-[11px] font-semibold text-slate-600 mb-1 flex items-center gap-1">
                <GraduationCap class="w-3 h-3 text-slate-400" />
                Student ID
              </label>
              <input
                v-model="studentId"
                type="text"
                class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-lg text-xs font-medium text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                placeholder="Enter Student ID"
              />
            </div>

            <div>
              <label class="block text-[11px] font-semibold text-slate-600 mb-1 flex items-center gap-1">
                <Calendar class="w-3 h-3 text-slate-400" />
                Course Title
              </label>
              <input
                v-model="courseName"
                type="text"
                class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-lg text-xs font-medium text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                placeholder="Enter Course Title"
              />
            </div>
          </div>
        </div>

        <!-- Markdown Live Preview -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <span class="text-xs font-semibold text-slate-700 uppercase tracking-wider font-mono">
              Generated Report Preview (Markdown)
            </span>
            <span class="text-xs text-slate-500 font-mono">
              {{ benchmarkResults.length }} Benchmark Records Logged
            </span>
          </div>
          <pre class="p-4 bg-slate-900 text-slate-100 rounded-xl font-mono text-xs overflow-x-auto max-h-72 whitespace-pre-wrap border border-slate-800 shadow-inner leading-relaxed">{{ markdownReport }}</pre>
        </div>
      </div>

      <!-- Modal Footer & Action Buttons -->
      <div class="p-4 border-t border-slate-200 bg-slate-50 flex flex-wrap items-center justify-between gap-3">
        <div class="text-[11px] text-slate-500 font-mono">
          Ready to attach to coursework submission
        </div>
        <div class="flex flex-wrap items-center gap-2">
          <a
            href="/Benchmark.txt"
            download="Benchmark.txt"
            class="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 transition-all flex items-center gap-1.5 shadow-xs"
          >
            <Download class="w-3.5 h-3.5 text-sky-600" />
            Download Benchmark.txt
          </a>
          <a
            href="/Reflection.md"
            download="Reflection.md"
            class="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 transition-all flex items-center gap-1.5 shadow-xs"
          >
            <Download class="w-3.5 h-3.5 text-indigo-600" />
            Download Reflection.md
          </a>
          <button
            @click="handleDownloadJson"
            class="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 transition-all flex items-center gap-1.5 shadow-xs"
          >
            <Download class="w-3.5 h-3.5" />
            JSON Data
          </button>
          <button
            @click="handleCopyMarkdown"
            class="px-4 py-1.5 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-700 text-white transition-all flex items-center gap-1.5 shadow-xs"
          >
            <Check v-if="copied" class="w-3.5 h-3.5 text-emerald-300" />
            <Copy v-else class="w-3.5 h-3.5" />
            {{ copied ? 'Copied!' : 'Copy Markdown' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// React/src/components/LabReportModal.tsx
import React, { useState } from 'react';
import { BenchmarkResult } from '../types';
import { FRAMEWORKS, BENCHMARK_OPERATIONS } from '../data/frameworksData';
import { X, Copy, Download, Check, FileText } from 'lucide-react';

interface LabReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  benchmarkResults: BenchmarkResult[];
  itemCount: number;
}

export const LabReportModal: React.FC<LabReportModalProps> = ({
  isOpen,
  onClose,
  benchmarkResults,
  itemCount,
}) => {
  const [studentName, setStudentName] = useState('Student Researcher');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Generate markdown report content
  const generateMarkdownReport = () => {
    let md = `# Front-End JavaScript Frameworks DOM Performance Benchmark Report\n`;
    md += `**Author / Student:** ${studentName}\n`;
    md += `**Date:** ${new Date().toLocaleDateString()}\n`;
    md += `**Benchmark Workload Item Count:** ${itemCount.toLocaleString()} tasks\n\n`;

    md += `## 1. Executive Summary & Objective\n`;
    md += `The objective of this exercise is to benchmark and compare the performance of popular front-end JavaScript frameworks (React, Angular, Vue, and Svelte) in handling DOM manipulations through hands-on testing of To-Do list operations.\n\n`;

    md += `## 2. Experimental Benchmark Results\n\n`;
    md += `| Framework | Operation | Item Count | Duration (ms) | DOM Operations | Est. Memory (KB) | FPS Score |\n`;
    md += `|-----------|-----------|------------|---------------|----------------|------------------|-----------|\n`;

    benchmarkResults.forEach((r) => {
      const fw = FRAMEWORKS[r.framework]?.name || r.framework;
      const op = BENCHMARK_OPERATIONS.find((o) => o.id === r.op)?.name || r.op;
      md += `| ${fw} | ${op} | ${r.itemCount.toLocaleString()} | ${r.durationMs} ms | ${r.domMutations} | ${r.memoryEstKb} KB | ${r.fps} |\n`;
    });

    md += `\n## 3. Architectural Key Takeaways\n`;
    md += `- **React (Virtual DOM):** Uses runtime Fiber reconciliation tree diffing. Excellent for complex state trees, but allocates temporary VNode objects in memory.\n`;
    md += `- **Angular (Ivy LViews & Signals):** Compiles templates into instruction sets. Signals enable targeted binding updates without broad change detection passes.\n`;
    md += `- **Vue (Reactive Proxy & Block Trees):** Combines fine-grained ES6 Proxies with compiler Block Trees, skipping static DOM nodes during diffing passes.\n`;
    md += `- **Svelte (Compile-Time Direct DOM):** Operates with zero Virtual DOM overhead by compiling templates directly into native browser DOM mutations.\n\n`;

    md += `---\n*Report generated via DOM Benchmark Lab*`;
    return md;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(
      {
        studentName,
        date: new Date().toISOString(),
        itemCount,
        results: benchmarkResults,
      },
      null,
      2
    );
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dom-benchmark-report-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-fadeIn">
      <div className="bg-white border border-slate-200 rounded-2xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="p-6 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-amber-50 text-amber-800 border border-amber-200">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-slate-900">Student Lab Report Preview</h3>
              <p className="text-xs text-slate-500">
                Formatted benchmark report ready for assignment submission.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-6 custom-scrollbar text-xs text-slate-700">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 rounded-xl bg-slate-50 border border-slate-200">
            <div className="w-full sm:w-auto space-y-1">
              <label className="text-[10px] uppercase font-bold text-slate-500 font-mono">
                Student Name / ID
              </label>
              <input
                type="text"
                value={studentName}
                onChange={(e) => setStudentName(e.target.value)}
                className="w-full sm:w-64 px-3 py-1.5 text-xs bg-white border border-slate-200 rounded-lg text-slate-900 font-medium focus:outline-none focus:border-indigo-600"
              />
            </div>
            <div className="text-right text-slate-500 font-mono text-[11px]">
              <div>Workload: <strong className="text-slate-900">{itemCount.toLocaleString()} items</strong></div>
              <div>Recorded Runs: <strong className="text-emerald-600">{benchmarkResults.length}</strong></div>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="text-sm font-bold text-slate-900 font-mono">Recorded Benchmark Data Table</h4>
            <div className="overflow-x-auto border border-slate-200 rounded-xl bg-white">
              <table className="w-full text-left font-mono text-[11px]">
                <thead className="bg-slate-50 text-slate-500 border-b border-slate-200">
                  <tr>
                    <th className="p-2.5">Framework</th>
                    <th className="p-2.5">Operation</th>
                    <th className="p-2.5">Time (ms)</th>
                    <th className="p-2.5">DOM Ops</th>
                    <th className="p-2.5">Est. Memory</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {benchmarkResults.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="p-4 text-center text-slate-400 font-sans">
                        No benchmark data recorded. Run benchmarks first!
                      </td>
                    </tr>
                  ) : (
                    benchmarkResults.map((r) => (
                      <tr key={r.id}>
                        <td className="p-2.5 font-bold text-slate-900">{FRAMEWORKS[r.framework]?.name || r.framework}</td>
                        <td className="p-2.5 text-slate-700">{r.op}</td>
                        <td className="p-2.5 text-emerald-600 font-bold">{r.durationMs} ms</td>
                        <td className="p-2.5 text-sky-600">{r.domMutations}</td>
                        <td className="p-2.5 text-amber-600">{r.memoryEstKb} KB</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

          <div className="space-y-2">
            <h4 className="text-sm font-bold text-slate-900 font-mono">Generated Markdown Preview</h4>
            <pre className="p-4 rounded-xl bg-slate-50 border border-slate-200 font-mono text-[11px] text-slate-800 overflow-x-auto max-h-48 leading-relaxed custom-scrollbar">
              <code>{generateMarkdownReport()}</code>
            </pre>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="text-[11px] text-slate-500 font-mono">
            Ready to attach to coursework submission
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <a
              href="/Benchmark.txt"
              download="Benchmark.txt"
              className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 transition-all flex items-center gap-1.5 shadow-xs"
            >
              <Download className="w-3.5 h-3.5 text-sky-600" />
              Download Benchmark.txt
            </a>
            <a
              href="/Reflection.md"
              download="Reflection.md"
              className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 transition-all flex items-center gap-1.5 shadow-xs"
            >
              <Download className="w-3.5 h-3.5 text-indigo-600" />
              Download Reflection.md
            </a>
            <button
              onClick={handleDownloadJson}
              className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 transition-all flex items-center gap-1.5 shadow-xs"
            >
              <Download className="w-3.5 h-3.5" />
              JSON Data
            </button>
            <button
              onClick={handleCopyMarkdown}
              className="px-4 py-1.5 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-700 text-white transition-all flex items-center gap-1.5 shadow-xs"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-300" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied!' : 'Copy Markdown'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
